### ISSUE TITLE
Project gives sdk dependency errors

### ISSUE THREAD

**Issue by Rockvole** [moznion/dart-grec-minimal#1]
Its quite easy to fix the errors by updating your pubspec.yaml to this :

    name: grec_minimal
    description: A minimal parser/generator of recurrence rule for Google Calendar
    version: 0.0.3
    homepage: https://github.com/moznion/dart-grec-minimal
    author: moznion <moznion@gmail.com>

    environment:
      sdk: '>=2.1.0 <3.0.0'

    dev_dependencies:
      test: ^1.5.1+1

**Comment by moznion** [comment]
Thanks for the heads up.
If it's not too much trouble, send me a pull-request please.

**Comment by Rockvole** [comment]
Cool thanks - can update pub ?
Your package shows an error because it is out of date.
https://pub.dartlang.org/packages/grec_minimal

**Comment by moznion** [comment]
I've published the latest one. Could you try it?

**Comment by Rockvole** [comment]
Yes, it is good from pub now :)
