### ISSUE TITLE
example of use

### ISSUE THREAD

**Issue by limdnas** [moznion/dart-grec-minimal#3]
hello,

how i can add a recurrence day widget to a calendar like this:

https://pub.dartlang.org/packages/flutter_calendar_carousel

Thank you a lot¡¡¡

**Comment by limdnas** [comment]
for example:

1,1,2,2,3,3,4,4,4,4,4,1,  1,2,2,3,3,4,4,4,4,4,1,  1,2,2,3,3,4,4,4,4,4,1,  1,2,2,3,3,4,4,4,4,4,........

to all calendar

**Comment by moznion** [comment]
Probably this isn't related to this library, I close this.
