### ISSUE TITLE
Any Plans to Add BYMONTHDAY?

### ISSUE THREAD

**Issue by dkobia** [moznion/dart-grec-minimal#4]
Currently there's no way to create a ByMonthDay rule e.g. `Monthly on the 2nd and 15th of the month`, which translates to `RRULE:FREQ=MONTHLY;COUNT=10;BYMONTHDAY=2,15`. At the moment this rule is parsed to `RRULE:FREQ=MONTHLY;COUNT=10`.

**Comment by moznion** [comment]
I'm sorry for my late reply. I'll consider that.

**Comment by moznion** [comment]
I'm sorry for waiting you for a long time.
I've just released a new version `0.0.4` that supports `BYMONTHDAY`: https://pub.dev/packages/grec_minimal
